[package]
name = "awful-idea-name"
version = "0.3.0"
authors = ["Timothy Warrington <tim.warrin@gmail.com>"]
edition = "2018"
description = "Generate awful idea names for your next awful idea"
license = "MIT/Apache-2.0"

[dependencies]
rand = "0.7.3"

[dev-dependencies]
regex = "1.3.9"
